### ISSUE TITLE
Reference section missing in most chapters

### ISSUE THREAD

**Issue by alignan** [marcozennaro/IPv6-WSN-book#10]
Add a reference chapter :-)

**Comment by alvarovives** [comment]
I agree, we can add a reference chapter at the end of the book, better than having references en each chapter. If people agree I can do that

**Comment by alignan** [comment]
Assigned! I will help you as well.

**Comment by alvarovives** [comment]
OK, I created a new references chapter at the end of the book and moved there all the references I found. I don't know why this time I commited to the master branch...

**Comment by alignan** [comment]
Great! https://github.com/marcozennaro/IPv6-WSN-book/commit/2db1a2de3d745e6e6b7108f4a3cf32714aa123e5 fixes #10
