### ISSUE TITLE
Cooja simulation not related to gogo6/HE sections

### ISSUE THREAD

**Issue by alignan** [marcozennaro/IPv6-WSN-book#11]
Either move to a different chapter or to an annex section.

**Comment by alignan** [comment]
As `day 4` mentions the option to have gogo6 or HE to setup an IPv6 tunnel, this needs to be ammended here as well, either to a reference to an annex, or by including a subchapter before day 4.

**Comment by alvarovives** [comment]
I propose to change the order of the contents, to follow Costa Rica workshop agenda.
So we can start with all the IPv6, gogo6 or HE, 6LowPAN, ROLL.
If people agree I can make this changes and be in charge of this content.

**Comment by alignan** [comment]
Agree, we had a first iteration at the ICTP workshop, we can improve this :-)

Please propose a Table of Contents, we can review and change the document.

**Comment by alvarovives** [comment]
My Proposed ToC is:

1 Introduction to IoT  (i.asc)

2 Introduction to IPv6 (0.asc)

3 Connecting our network to the world (3.asc)
  NOTE: I'd take the first part of this section and leave the cooja part from 3.asc. Also I'l take the "Setting up IPv6 using gogo6" and "Setting up IPv6 using Hurricane Electric" sections.

4 Intro to 6LoWPAN (2.asc)

5 Installing 6lbr on a Raspberri Pi (5.asc)
  NOTE: I'd put here sections "Installing 6lbr on a Raspberri Pi","Using NAT64 with wrapsix" and "Launching 6lbr as Border Router with NAT64".
  I'm not sure why NAT64 is needed here.

6 Short introduction to Contiki  (1.asc)

7 Wireless with Contiki (2.asc)

8 IoT Simulation (Cooja) (3.asc)

9 IPv6 communication in Contiki and IoT/M2M protocols (4.asc) 

10 Sending Data to Ubidots  (1.asc) / End-to-end IPv6 communication with an IoT platform (5.asc)

11 References (ref.asc)

Please, provide your feedback here.
I you think this is OK, I can change the files to follow this ToC.

**Comment by alignan** [comment]
I will review this later and provide comments, this should also fix #4 if done properly, thanks for the work Alvaro!

**Comment by alignan** [comment]
Notes after meeting (July 28):
- Remove 6lbr on chapter 5, instead use tunslip6 and explain basics on radvd, etc.
- Describe scenarios: IPv6 only, IPv6 network and IPv4 endpoint, etc.

**Comment by alignan** [comment]
I have created a new branch `rework` for the upcoming workshop.  

I have addressed the comments about the ToC, and going to start cleaning up sections and examples.  It is a working branch, I will create another more stable branch (`walc2015`) later with commits suitable for revision.

For the moment avoid merging/pushing to master.

Cheers!
