### ISSUE TITLE
How can I cite this book?

### ISSUE THREAD

**Issue by shantanoo-desai** [marcozennaro/IPv6-WSN-book#12]
Hello, 
Thanks for this book and it is really helpful for someone beginning their work in IoT and WSN.
I would like to cite this book in some documentation I am working on. 
Is there any BibTeX citation available or in general a format which I should follow?

Thanks,
Shan

**Comment by marcozennaro** [comment]
Hi Shan,

thank you for your message! We don't have a BibTeX citation yet. You can use this link if you want to cite the book: http://wireless.ictp.it/school_2015/book/

Thanks and I'll keep you updated on the status. We are now working on slides to go with the book.

Best,
Marco

**Comment by shantanoo-desai** [comment]
Hi Marco, 
Maybe I will try finding some solution out for a BibTeX citation, and post it here and let me know if it works.

**Comment by shantanoo-desai** [comment]
```
@Book{WSN-book,
    title = {{IoT in 5 Days}},
    author = {Antonio Linan Colina and Alvaro Vives and Antoine Bagula and Marco Zennaro and Ermanno Pietrosemoli},
    publisher = {E-Book},
    year = {2015},
    month = {march},
    note = {Rev 1.0},
    url = {http://http://wireless.ictp.it/school_2015/book/}
}
```

BibTeX citation, changed welcome

**Comment by marcozennaro** [comment]
Looks great! Thanks!

Marco

**Comment by alignan** [comment]
Thanks for the contribution!

As the book will run into new changes for an upcoming workshop, and towards a more stable release, please consider using the following instead:

```
@Book{WSN-book,
    title = {{IoT in 5 Days}},
    author = {Antonio Linan Colina and Alvaro Vives and Antoine Bagula and Marco Zennaro and Ermanno Pietrosemoli},
    publisher = {E-Book},
    year = {2015},
    month = {march},
    note = {Rev 1.0},
    url = {https://github.com/marcozennaro/IPv6-WSN-book/releases/}
}
```

I will update the README with this.

Cheers!
