### ISSUE TITLE
IPv6 Address in image seems to be wrong

### ISSUE THREAD

**Issue by tonnenpinguin** [marcozennaro/IPv6-WSN-book#13]
In file [/images/1/image006.png](https://github.com/marcozennaro/IPv6-WSN-book/blob/master/images/1/image006.png) there are four LAN devices connected to two LANs. While the first two devices have correct IP addresses I believe that the other two IP addresses should have a `<2001:db8:1:3::/64>` prefix as mentioned in the text.

![image006.png](https://github.com/marcozennaro/IPv6-WSN-book/blob/master/images/1/image006.png)

**Comment by tonnenpinguin** [comment]
One general question: As I have been reading through the text (a big thank you by the way) I noticed several minor bugs/typos...what is your preferred way of handling this? Should I prepare a pull request fixing at least the text parts and open issues for the images?

**Comment by alignan** [comment]
Please make a PR, we keep the book open to encourage contributions :+1:

**Comment by tonnenpinguin** [comment]
Will do, but the image I can't fix :)

**Comment by alvarovives** [comment]
Thanks a lot for pointing out the mistake on the Network figure! It's corrected now.
