### ISSUE TITLE
Help with MSP430-GCC toolchain

### ISSUE THREAD

**Issue by shantanoo-desai** [marcozennaro/IPv6-WSN-book#14]
Hi guys,

Following the book to setup Contiki on a Laptop with following details:
- **32-bit Ubuntu 14.04 LTS Trusty Tahr** with **Jessie/sid**

Following the toolchain and dependencies section as mentioned [Install-from-sources](https://github.com/marcozennaro/IPv6-WSN-book/blob/master/3.asc#install-from-sources)

this is what I get when I do `apt-key` command

```
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --
homedir/tmp/tmp.aBpmlMxM2u --no-auto-check-trustdb --trust-model always --keyring 
/etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver keyserver.ubuntu.com
--recv-key FE324A81C208C89497EFC6246D1D8367A3421AFB
gpg: requesting key A3421AFB from hkp server keyserver.ubuntu.com
gpg: key A3421AFB: "Launchpad PPA for Terry Guo" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
```

when I do `apt-get update`

<pre>
W: Failed to fetch http://de.archive.ubuntu.com/ubuntu/dists/trusty/InRelease  

W: Failed to fetch http://de.archive.ubuntu.com/ubuntu/dists/trusty-updates/InRelease  

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease  

W: Failed to fetch http://ppa.launchpad.net/terry.guo/gcc-arm-embedded/ubuntu/dists/trusty/InRelease  

W: Failed to fetch http://de.archive.ubuntu.com/ubuntu/dists/trusty/Release.gpg  Could not resolve 'files'

W: Failed to fetch http://de.archive.ubuntu.com/ubuntu/dists/trusty-updates/Release.gpg  Could not resolve 'files'

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/Release.gpg  Could not resolve 'files'

W: Failed to fetch http://ppa.launchpad.net/terry.guo/gcc-arm-embedded/ubuntu/dists/trusty/Release.gpg  Could not resolve 'files'

W: Some index files failed to download. They have been ignored, or old ones used instead.
  
</pre>

For the time being I have ignored this issue and went on to further install the toolchains

for MSP430-GCC I end up have the LTS version and not the development Patch

```
root@testbed:~# msp430-gcc --version
msp430-gcc (GCC) 4.6.3 20120301 (mspgcc LTS 20120406 unpatched)
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

The thing is I have faced such problems in the Past when I need application on Z1 where the ROM Overflow causes an Issue (when running **CoAP+RPL** for example) and I found that the LTS version does not allow the ROM changes as the Developement Patch version. 

There are some scripts where you can override the toolchain version like these : 
[ContikiWiki_MSP430X](https://github.com/contiki-os/contiki/wiki/MSP430X)
[Version4.7.2](https://github.com/tecip-nes/contiki-tres/wiki/Building-the-latest-version-of-mspgcc)

but I cannot get the developpatch nor the New version to load when I do `msp430-gcc --version`

any pro tips would be appreciated.

**Comment by alignan** [comment]
I cannot see how the errors are related to the gcc sources:

```
Failed to fetch http://de.archive.ubuntu.com/ubuntu/dists/trusty/InRelease  
```

You should repair your dependencies.

The `msp430-gcc` toolchain is available at:

https://sourceforge.net/projects/zolertia/files/Toolchain/

You need to download the `msp430-47`, unzip to a known location (I'm assuming `home/user`) then add this to your `PATH` as follows:

```
sudo $HOME/.bashrc
export PATH=/home/user/msp430-47/bin:$PATH
```

**Comment by shantanoo-desai** [comment]
Thanks will have a look into it. till then I will close the issue.
