### ISSUE TITLE
Viewing printf on Z1

### ISSUE THREAD

**Issue by bliz937** [marcozennaro/IPv6-WSN-book#15]
I think the info in the info bubble on page 62, _3.5.7 Analogue Sensors_, should be made available earlier in the chapter as **printf** is mentioned early in the chapter but not how to access it. 

More specifically:

> make login prints to console the output of any printf command in our code

**Comment by alignan** [comment]
Thanks for the feedback! you are right, this should be shown sooner

**Comment by alignan** [comment]
Fixes https://github.com/marcozennaro/IPv6-WSN-book/commit/126510880cddd9328c61fea3c37a9920cc698993
